# general data
title: Labion ESP32
email: lautisilbergleit@gmail.com
description: Meassure, log and water your plants in your laboratory automatically!
github_username: lautisilber

# build settings
exclude: ['README.md']
markdown: kramdown
theme: jekyll-theme-cayman
show_downloads: true
